# Generated by Django 2.1.2 on 2018-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, null=True)),
                ('time', models.CharField(max_length=60, null=True)),
                ('iowait', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('guest_nice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('user', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('system', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('guest', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('steal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('irq', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('idle', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('softirq', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'cpuinfo_tbl',
            },
        ),
        migrations.CreateModel(
            name='DiskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, null=True)),
                ('time', models.CharField(max_length=60, null=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('free', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('used', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'diskinfo_tbl',
            },
        ),
        migrations.CreateModel(
            name='MemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, null=True)),
                ('time', models.CharField(max_length=60, null=True)),
                ('active', models.IntegerField(default=0, null=True)),
                ('available', models.IntegerField(default=0, null=True)),
                ('used', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('shared', models.IntegerField(default=0, null=True)),
                ('inactive', models.IntegerField(default=0, null=True)),
                ('buffers', models.IntegerField(default=0, null=True)),
                ('cached', models.IntegerField(default=0, null=True)),
                ('free', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'meminfo_tbl',
            },
        ),
        migrations.CreateModel(
            name='NetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('recv', models.IntegerField(default=0, null=True)),
                ('sent', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'netinfo_tbl',
            },
        ),
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, null=True)),
                ('time', models.CharField(max_length=60, null=True)),
                ('trace', models.CharField(max_length=300, null=True)),
                ('port_status', models.CharField(max_length=30, null=True)),
                ('ping', models.CharField(max_length=30, null=True)),
                ('p_ip', models.CharField(max_length=45, null=True)),
                ('p_port', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'partnerinfo_tbl',
            },
        ),
        migrations.CreateModel(
            name='PlatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, null=True)),
                ('time', models.CharField(max_length=60, null=True)),
                ('cpu_num', models.IntegerField(default=0, null=True)),
                ('release1', models.CharField(max_length=120, null=True)),
                ('dist', models.CharField(max_length=90, null=True)),
                ('machine', models.CharField(max_length=30, null=True)),
                ('system', models.CharField(max_length=45, null=True)),
                ('boot_time', models.CharField(max_length=60, null=True)),
            ],
            options={
                'db_table': 'platinfo_tbl',
            },
        ),
        migrations.CreateModel(
            name='SwapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, null=True)),
                ('time', models.CharField(max_length=60, null=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('free', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('used', models.IntegerField(default=0, null=True)),
                ('sin', models.IntegerField(default=0, null=True)),
                ('sout', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'swapinfo_tbl',
            },
        ),
    ]
